version: 2
project_name: driftsync

builds:
  - id: driftsync
    main: ./cmd/driftsync
    env: [CGO_ENABLED=0]
    ldflags: [-s -w]
    goos: [linux, windows]
    goarch: [amd64, arm64]

archives:
  - id: by_os
    builds: [driftsync]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      # - config.yaml   # 将来真有再取消注释

nfpms:
  - id: linux-packages
    package_name: driftsync
    builds: [driftsync]     # 关键：和上面的 build 关联
    formats: [deb, rpm]
    bindir: /usr/bin        # 二进制会自动安装到这里
    section: utils
    priority: optional
    license: MIT
    maintainer: caden <xiaochun.zh@outlook.com>
    description: "DriftSync — fast, reliable drift-aware sync tool."
    homepage: "https://github.com/xiaochun-z/driftsync"

release:
  draft: true
  name_template: "DriftSync {{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude: ['^docs:', '^test:']
