
tenant: consumers
client_id: 3ae224c9-f16c-42d1-bf5d-44151f2b99fa
local_path: "local_files"
download_from_cloud: true
upload_from_local: true
log:
  verbose: true
sync:
  include:
    - "/DriftSync_E2E_Test"
  exclude:
    - "*.ignore"
