// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRemoteItems(arg1) {
  return window['go']['main']['App']['GetRemoteItems'](arg1);
}

export function GetStartOverPaths() {
  return window['go']['main']['App']['GetStartOverPaths']();
}

export function LocateFile(arg1) {
  return window['go']['main']['App']['LocateFile'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartOver() {
  return window['go']['main']['App']['StartOver']();
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}
