// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {graph} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetRemoteItems(arg1:string):Promise<Array<graph.DriveItem>>;

export function GetStartOverPaths():Promise<Array<string>>;

export function LocateFile(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetWorkspaceLocation(arg1:string):Promise<void>;

export function StartOver():Promise<void>;

export function StartSync():Promise<void>;

export function StopSync():Promise<void>;
