name: Release (multi-OS + deb/rpm, draft)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # 必须：用来创建 release 并上传资产

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # goreleaser 需要完整 git 历史

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      # 可选：若你用到 CGO，安装交叉编译工具链（当前配置 CGO_DISABLED=1，不需要）
      # - name: Install cross deps
      #   run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --timeout=60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
