name: Build DriftSync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Create config.yaml
      run: |
        cat > config.yaml << 'EOF'
        client_id: "test"
        client_secret: "test"
        redirect_uri: "http://localhost:8080/callback"
        EOF
    
    - name: Build
      run: go build -o driftsync ./cmd/driftsync
    
    - name: Test
      run: |
        chmod +x driftsync
        ./driftsync --help
        echo "SUCCESS!"
    
    - uses: actions/upload-artifact@v4
      with:
        name: driftsync-binary
        path: driftsync
